#!/usr/bin/env bash
# A script that prints a message when receiving SIGTERM instead of terminating

# Add this line to the script:
trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
