#!/usr/bin/env bash
# 7-highlander - Displays a message indefinitely and handles SIGTERM

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM (signal 15)
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
