#!/usr/bin/env bash
# A script that prints a message when receiving SIGTERM instead of terminating
# Trap SIGTERM to print your message
trap "echo 'I am invincible!!!'" SIGTERM

while true
do
    echo "To infinity and beyond"
    # Run sleep in background and wait for its PID ($!)
    sleep 2 & wait $!
done
