#!/bin/bash

# Initialize the counter
counter=1

# Use a while loop to iterate from 1 to 20
while [ $counter -le 20 ]
do
    # Use a case statement to check for specific numbers
    case $counter in
        4)
            echo "4 and then bad luck from China"
            ;;
        9)
            echo "9 and then bad luck from Japan"
            ;;
        17)
            echo "17 and then bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    # Increment the counter
    ((counter++))
done
